Enhance project configuration: update .gitignore, add nuget.config, and introduce .editorconfig and CODE_OF_CONDUCT.md

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,16 +8,13 @@ stages:
 before_script:
   - 'export DOTNET_CLI_TELEMETRY_OPTOUT=1'
   - 'export PATH=$PATH:$HOME/.dotnet/tools'
-  - 'dotnet tool install JetBrains.ReSharper.GlobalTools --global || echo "JB already installed."'
-  - 'dotnet tool install dotnet-reportgenerator-globaltool --global || echo "DRG already installed."'
-  - 'cat /etc/lsb-release && uname -a && pwd && ls -ashl'
+  - 'which jb || dotnet tool install JetBrains.ReSharper.GlobalTools --global --add-source https://nuget.aiursoft.cn/v3/index.json --configfile ./nuget.config -v d'
+  - 'which reportgenerator || dotnet tool install dotnet-reportgenerator-globaltool --global --add-source https://nuget.aiursoft.cn/v3/index.json --configfile ./nuget.config -v d'
   - 'echo "Hostname: $(hostname)"'
-  - 'echo "Uptime: $(uptime -p)"'
-  - 'echo "Memory: $(free -h | awk "/^Mem:/{print \$2}")"'
-  - 'echo "CPU Cores: $(nproc)"'
-  - 'echo "Available Disk Space: $(df -h --output=avail / | tail -1)"'
-  - 'echo "IP Address: $(hostname -I)"'
   - 'dotnet --info'
+
+variables:
+  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'
 
 restore:
   stage: build
@@ -36,7 +33,12 @@ lint:
   needs: 
     - build
   script:
-    - jb inspectcode ./*.sln --output=analyze_output.xml --build
+    # 3 times retry because sometimes the first time will fail
+    - jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml || jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml || jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml
+    # Remove the warning of UnusedAutoPropertyAccessor InconsistentNaming
+    - sed -i '/InconsistentNaming/d' analyze_output.xml
+    - sed -i '/AssignNullToNotNullAttribute/d' analyze_output.xml # This is because jetbrains is not smart enough to understand the nullability of C# 8.0
+    - sed -i '/UnusedAutoPropertyAccessor/d' analyze_output.xml
     - grep 'WARNING' analyze_output.xml && cat analyze_output.xml && exit 1 || echo "No warning found"
   artifacts:
     when: always
@@ -68,14 +70,6 @@ test:
         coverage_format: cobertura
         path: ./Cobertura.xml
 
-publish:
-  stage: publish
-  needs: 
-    - lint
-    - test
-  script:
-    - dotnet publish -maxcpucount:1 --configuration Release --runtime linux-x64 --no-self-contained *.sln
-
 pack:
   stage: publish
   needs: 
@@ -89,22 +83,7 @@ pack:
     paths:
       - '**/*.nupkg'
 
-upload_to_nuget:
-  stage: deploy
-  environment: production
-  needs:
-    - pack
-  dependencies:
-    - pack
-  script:
-    - |
-      for file in $(find . -name "*.nupkg"); do
-        dotnet nuget push "$file" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate || exit 1;
-      done
-  only:
-    - master
-
-upload_to_local_nuget:
+deploy_local_nuget:
   stage: deploy
   environment: production
   needs:
@@ -119,16 +98,50 @@ upload_to_local_nuget:
   only:
     - master
 
-deploy_docker:
+deploy_public_nuget:
   stage: deploy
   environment: production
   needs:
-    - publish
+    - pack
+    - deploy_local_nuget
   dependencies:
-    - publish
+    - pack
   script:
+    - |
+      for file in $(find . -name "*.nupkg"); do
+        dotnet nuget push "$file" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate || exit 1;
+      done
+  only:
+    - master
+
+deploy_docker_registry:
+  stage: deploy
+  environment: production
+  needs: 
+    - lint
+    - test
+  script:
+    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
+    - echo building image hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
     - docker build . -t hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
     - docker push hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "master"'
+      exists:
+      - Dockerfile
+
+deploy_docker_hub:
+  stage: deploy
+  environment: production
+  needs: 
+    - deploy_docker_registry
+  script:
+    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
+    - echo building image $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
+    - docker build . -t $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
+    - echo "Logging in to Docker Hub..."
+    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+    - docker push $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
   rules:
     - if: '$CI_COMMIT_BRANCH == "master"'
       exists:
